Repository hackforla/website, pull requests merged in 2019-05, with the labels that each got.

#82 Simplify Docker setup, improve Jekyll server
  Dockerfile
  README.md
  _config.docker.yml
  _layouts/default.html
  _sass/components/_hero.scss
  assets/css/main.scss
  docker-compose.yml
Labels: admin, enhancement

#90 Fix scss variable for absolute_url
  assets/css/main.scss
Labels: bug

#107 Implement redirects for gh-pages
  _layouts/redirect.html
  calendar.md
  conduct.md
  donate.md
  github.md
  meetup.md
  slack.md
Labels: priority
