Repository hackforla/website, pull requests merged in 2021-06, with the labels that each got.

#1740 Create add-issue-labels-to-pr.yml
  .github/workflows/add-issue-labels-to-pr.yml
Labels: Medium, back end, enhancement

#1751 Update CONTRIBUTING.md with the "How to Review Pull Requests" Wiki
  CONTRIBUTING.md
Labels: Good first issue, documentation

#1764 Change Alt Text for Meetup Logo
  _data/internal/credits/button.yml
Labels: Good first issue, accessibility

#1763 Replace alt text in people2.yml from 'Image of people' to 'Fireside discussion concept illustration'
  _data/internal/credits/people2.yml
Labels: Good first issue, accessibility

#1765 Resume alt text
  _data/internal/credits/resume.yml
Labels: Size: Good first issue, accessibility

#1471 Contributing.md changes
  CONTRIBUTING.md
Labels: To Update !, documentation

#1785 Wins badge change setup to set up
  pages/wins/wins-share-form.html
  pages/wins/wins.html
Labels: Feature: Wins Page, Size: Medium, role: front end

#1780 Updated the alt attribute value for Design Image
  _data/internal/credits/design.yml
Labels: Size: Good first issue, accessibility

#1784 Update alt text for "Technology" image within the "Credits" page
  _data/internal/credits/technology.yml
Labels: Feature: Accessibility, Size: Good first issue

#1774 Adjusts Program Areas page image cards in mobile
  _sass/components/_program-areas.scss
Labels: Size: Medium, role: front end

#1782 Change alt text
  _data/internal/credits/photo-roster.yml
Labels: Feature: Accessibility, Size: Good first issue

#1783 changed alt text for Partnership Icon on Credit page
  _data/internal/credits/partnership.yml
Labels: Feature: Accessibility, Size: Good first issue

#1804 changed alt office worker
  _data/internal/credits/office-worker.yml
Labels: Feature: Accessibility, Size: Good first issue

#1801 changed alt text for designer life image on credits page
  _data/internal/credits/designer-life.yml
Labels: Feature: Accessibility, Size: Good first issue

#1799 add missing periods in the Getting Started Page
  pages/getting-started.html
Labels: P-Feature: Getting Started, Size: Good second issue, role: front end

#1790 remove margin: auto to split header paragraphs on cop page
  _sass/components/_communities-of-practice.scss
Labels: Size: Good second issue, role: front end

#1773 Adding button xl-long class and applying it to CTA "Join Us" home page button
  _includes/home-getting-started.html
  _sass/elements/_buttons.scss
  _sass/elements/_typography.scss
  _sass/variables/_typography.scss
Labels: P-Feature: Home page, Size: Good second issue, role: front end

#1813 Fix "Online Project Team Meetings" button in mobile view within Events Page
  _sass/components/_events.scss
  pages/events/right-col-content.html
Labels: P-Feature: Events, Size: Good second issue, role: front end

#1731 Standardize join us page mobile
  _sass/components/_join-us.scss
  pages/join-us.html
Labels: P-Feature: Credit, P-Feature: Join Page, Size: Medium, To Update !, role: front end

#1821 Rename security.yml
  _data/internal/credits/security.yml
Labels: Bug, Feature: Standards, Size: Good first issue

#1827 issue 1570, change email alt text
  _data/internal/credits/email.yml
Labels: Feature: Accessibility, Size: Good first issue

#1831 Update Toolkit page's filter banner font weight
  _sass/components/_toolkit.scss
Labels: Feature: Refactor CSS, Size: Good second issue, role: front end

#1854 Added documentation for unseen changes
  CONTRIBUTING.md
Labels: Bug, Feature: Onboarding/Contributing.md, Status: Updated, documentation, role: writing

#1853 removed max height property so all getting started cards were visible
  _sass/components/_project-page.scss
Labels: Bug, P-Feature: Project Info and Page, Size: Good second issue, role: front end

#1775 Add x modal wins page
  _sass/components/_wins-page.scss
  assets/images/wins-page/x.svg
  pages/wins/wins-overlay.html
Labels: Feature: Refactor JS / Liquid, P-Feature: Wins Page, Size: Medium, role: front end

#1814 Implementing new design system heading typography in the code base
  _sass/core/_print.scss
  _sass/elements/_typography.scss
  _sass/variables/_typography.scss
Labels: Feature: Design system, Size: Medium, role: front end

#1855 Add media query to .leader-description
  _sass/components/_project-page.scss
Labels: Bug, P-Feature: Project Info and Page, Size: Good second issue, role: front end
