Repository hackforla/website, pull requests merged in 2023-12, with the labels that each got.

#5883 Create Issue Template for adding github-handle to leadership member data in project file. #5541
  .github/ISSUE_TEMPLATE/add-github-handle.md
Labels: role: back end/devOps, Complexity: Medium, P-Feature: Project Info and Page, ready for dev lead, size: 1pt

#5951 Removed Diedrich Chavarria
  _projects/lucky-parking.md
Labels: good first issue, role: front end, role: back end/devOps, P-Feature: Project Info and Page, time sensitive, size: 0.25pt

#5467 Fix bug and consolidate "Schedule Thursday" into "Schedule Monthly" 4788
  .github/workflows/issue-trigger.yml
  .github/workflows/schedule-monthly.yml
  .github/workflows/wr-schedule-monthly.yml
  github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js
  github-actions/trigger-schedule/github-data/contributors-data.js
  github-actions/trigger-schedule/list-inactive-members/comment-issue.js
  github-actions/trigger-schedule/list-inactive-members/create-new-issue.js
  github-actions/trigger-schedule/list-inactive-members/get-list.js
Labels: Bug, role: back end/devOps, time sensitive, Feature: Board/GitHub Maintenance, Feature: Refactor GHA, size: 8pt, Complexity: Extra Large

#5932 Accomplishments edit by year 4188
  _data/internal/accomplishments.yml
  _includes/about-page/about-card-accomplishments.html
  _sass/components/_about.scss
  assets/js/about.js
  pages/about.html
Labels: role: front end, Complexity: Large, P-Feature: About Us, P-Feature: Program Area, size: 5pt

#5947 Redeclare variable scope to local in 2FA.js page
  assets/js/2FA.js
Labels: role: front end, Complexity: Medium, size: 1pt, Feature: Code Alerts

#5957 Update cspell.json with term "Undebate"
  cspell.json
Labels: good first issue, role: front end, role: back end/devOps, size: 0.25pt, feature: spelling

#5961 updates external links by adding rel
  _includes/about-page/about-card-sponsors.html
Labels: good first issue, role: front end, role: back end/devOps, P-Feature: About Us, size: 0.25pt, Feature: Code Alerts

#5950 Resolve codeql alert4 5674
  _includes/resource-card.html
Labels: good first issue, role: front end, role: back end/devOps, size: 0.25pt, Feature: Code Alerts

#5977 Updated instructions for creating ~/.ssh prior to using ssh-keygen
  CONTRIBUTING.md
Labels: role: front end, role: back end/devOps, Feature: Wiki, Complexity: Small, size: 0.5pt

#6003 Refactored CSS so icon-slack.svg can use various colors
  _sass/elements/_icons.scss
Labels: good first issue, role: front end, role: back end/devOps, Feature: Refactor CSS, size: 0.25pt

#5955 Updated contributing.md 3.1.b VI
  CONTRIBUTING.md
Labels: role: front end, role: back end/devOps, Feature: Wiki, Complexity: Small, size: 0.5pt

#5976 Update vrms-data.yml to fail when the VRMS API fails to return a valid response 5691
  .github/workflows/vrms-data.yml
Labels: Bug, role: back end/devOps, Complexity: Medium, P-Feature: Project Info and Page, P-Feature: Events, size: 1pt

#6010 updates cspell.json casing
  cspell.json
Labels: good first issue, role: front end, role: back end/devOps, P-Feature: About Us, Feature: Infrastructure, size: 0.25pt, feature: spelling

#6004 Added 'test/' to ignorePaths array in cspell.json
  cspell.json
Labels: role: front end, role: back end/devOps, To Update !, Complexity: Small, size: 0.5pt, feature: spelling

#6006 Updated spell checker via cspell.json by adding 'Inclusivity'
  cspell.json
Labels: good first issue, role: front end, role: back end/devOps, P-Feature: About Us, Feature: Infrastructure, size: 0.25pt, feature: spelling

#6014 Update cspell.json with docker-compose.yml
  cspell.json
Labels: role: front end, role: back end/devOps, Complexity: Small, size: 0.5pt, feature: spelling

#6013 Update cspelljson with false positive term vrms
  cspell.json
Labels: good first issue, role: front end, role: back end/devOps, P-Feature: About Us, Feature: Infrastructure, size: 0.25pt, feature: spelling
